version: "3.6"
services:
  seller_agent:
    image: bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1
    environment:
      ADMIN_PORT: 5020
      AGENT_PORT: 10000
      INDY_SEED: ${SELLER_WALLET_SEED}
      SITE_URL: ${SELLER_SITE_URL}
      WEBHOOK_URL: http://paywall:5000/webhooks
      AGENT_LABEL: buyer Agent
    links:
      - paywall
    networks:
      - backend
    ports:
      - "5020:5020"
      - "10000:10000"
    restart: always
    entrypoint: /bin/bash
    command: [
        "-c",
        "curl -d '{\"seed\":\"${SELLER_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"SELLER AGENT (Docker)\"}' -X POST http://test.bcovrin.vonx.io/register; \
        sleep 5; \
        aca-py start \
        -it http '0.0.0.0' 10000 \
        -ot http \
        --admin '0.0.0.0' 5020 \
        -e $SELLER_SITE_URL \
        --wallet-type indy \
        --seed $SELLER_WALLET_SEED \
        --genesis-url http://test.bcovrin.vonx.io/genesis \
        --label 'seller Agent' \
        --auto-accept-invites \
        --auto-accept-requests \
        --admin-insecure-mode \
        --log-level info",
      ]


  paywall:
    image: paywall:latest
    build: .
    depends_on:
      - raiden
    restart: always
    links:
      - raiden
    networks:
      - backend
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "http://localhost:5000/webhooks"]
      interval: 1m30s
      timeout: 10s
      retries: 3



  raiden:
    command: --datadir /imports
    image: raidennetwork/raiden:demoenv001
    restart: always
    networks:
      - backend
    ports:
      - "5001:5001"
    volumes:
      - ./raiden_config:/imports
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v1/address"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 3m

networks:
  backend:
    driver: "bridge"
